personal_insights_questions = [
{"question":"How important is your cultural background to your identity?", "type":"text","placeholder":"Examples:Not important,Somewhat important,Very important"},
{"question":"Do you feel your cultural background affects your mental health?","type":"text","placeholder":"Yes/No; If yes, please explain how","placeholder":""},
{"question":"Do you face any discrimination or social stigma?","type":"text","placeholder":"Yes/No; If yes, please specify context and frequency","placeholder":""},
{"question":"How well do you feel that your cultural or personal identity aligns with societal expectations?","type":"text","placeholder":""},
{"question":"Do you face any challenges with language or communication in your daily life?","type":"text","placeholder":""},
{"question":"What are the core values that you live by?","type":"text","placeholder":""},
{"question":"From where or whom have you adopted most of your beliefs?","type":"text","placeholder":""},
{"question":"How do your values influence your decision-making processes?","type":"text","placeholder":""},
{"question":"Describe a situation where your values were challenged. How did you handle it?","placeholder":""},
{"question":"How do your values affect your relationships with others?","type":"text","placeholder":""},
{"question":"How do your values align with your professional life or career choices?","type":"text","placeholder":""},
{"question":"In what ways do you try to promote your values in your community or social circle?","type":"text","placeholder":""},
{"question":"How do your beliefs influence your daily behavior and interactions with others?","type":"text","placeholder":""},
{"question":"How do your beliefs impact your feelings of happiness or contentment?","type":"text","placeholder":""},
{"question":"Have you ever encountered situations where your beliefs were challenged? How did you react?","type":"text","placeholder":""},
{"question":"Can you provide examples of significant life decisions that were guided by your beliefs?","type":"text","placeholder":""},
{"question":"How has your identity evolved over the years? What factors have been most influential in shaping your identity?","type":"text","placeholder":""},
{"question":"Have you faced any challenges due to your identity? How have you addressed these challenges?","type":"text","placeholder":""},
{"question":"What aspects of your identity are you most proud of?","type":"text","placeholder":""},
{"question":"How do you define spirituality? Does it involve religious beliefs, personal philosophy, or something else?","type":"text","placeholder":""},
{"question":"How does spirituality manifest in your daily life?","type":"text","placeholder":""},
{"question":"Are you part of a spiritual community? How does this community support your spiritual growth?","type":"text","placeholder":""},
{"question":"How has your spirituality evolved over time? What events or experiences have led to significant changes in your spiritual outlook?","type":"text","placeholder":""},
{"question":"How does your spirituality influence your relationships with others?","type":"text","placeholder":""},
{"question":"What are the most important teachings or values you have learned from your spiritual beliefs?","type":"text","placeholder":""},
{"question":"Do you have any goals related to your spiritual life? What steps are you taking to achieve them?","type":"text","placeholder":""},
]